---
subtitle: "Kretzmann, Lex Inuista Non Est Lex"
title: "<font style='font-size:1em;'>🗓️ Week 03<br/> Phil Law</font>"
author: Prof. [Reynolds](#)
institute: '[Stetson University](#)'
date: 02 September 2026
date-meta: 14 March 2023
date-format: "DD MMM YYYY"
toc: false
toc-depth: 1
toc-title: "Laws on trial"
center-title-slide: false
from: markdown+emoji
format:
  revealjs:
    theme: moon
    fig-responsive: true
    font-size: 10
    slide-number: true
    incremental: true
    mouse-wheel: false
    auto-play-media: true
    preview-links: auto
    logo: /figures/icons/course_favicon.png
    css: /css/styles_slides.css
    footer: 'PHIL104Q -- Introduction to Logic'
---

# Introduction

## Three Questions

1. Can an individual citizen decide that the law is unjust?
2. What grounds should that individual citizen decide that the law is unjust?
3. If the judgment goes against the state, what is that citizen entitled or obliged to do about it?

## The Dismissive Judgment Regarding Unjust Laws

* The dismissive judgment.
* Examples of the judgments:

> Such societies, we are now, of course contending, are no constitutional states, just as enactments, so far as they are not for the common interest of the whole community, are no true laws (*Laws*, IV 715B)

## Hippias Major D

1. Laws are beneficial to the citizens of a community
2. Therefore law makers make laws to be to the greatest benefit of that community
3. So if law makers fail to make a good law, then law makers have failed to make a law

## Non Est Lex, the slogan and the issue

***Inclusion Conditions***

Here is an equivocation between evaluative judgments and ontological ones.

Claims about natural ontological inclusion conditions

> Many kinds of things have inclusion conditions that are entirely non-evaluative. For instance, it seems reasonable to suppose that no natural kinds have evaluative conditions among their inclusion among their standard inclusion conditions.

---

Claims about non-natural ontological inclusion conditions

* These are entirely non-evaluative, such as the iambic pentameter

The employee example is interesting. What makes an employee?:

* That they work?
* That they do just enough work?
* That they do not do any work but are still paid by an employer?

---

Overt and Invariable evaluative kinds:

* literary master piece, child prodigy

## Summary of the Traditional Slogan

> those who formulated wicked unjust statutes for nations, thereby breaking their promises and agreements, put into effect *anything* but laws. It may thus be clear that in the very definition of the term 'law there inheres the idea and principle of choosing what is just and true'".

I.e.,

Law == justice and truth

## Cases with evaluative and non-evaluative inclusion conditions

* Plagiarized term papers
* corrupt judges
* counter fit dollar bills

---

Difference between evaluative and ontological judgments.

* Is a corrupt judge still a judge?
* Is a lazy employee still an employee?

These judgments are different in kind from judgments about counter fit dollar bills but they are made analogously.

Lyon's rejects the slogan, Kretzmann finds truth in it that is not paradoxical.

---

1. Laws can intelligently be judged good or bad
2. Wise or foolish
3. Just or unjust.

## Conditional of Moral Legal Standards

> If there *are* moral standards by which laws may properly be judged, then it would seem that laws can *be* good or bad, just or unjust.

## Aquinas Moral Standards

Some Complications:

1. Misleading: laws framed by humans are either just or unjust.
2. How can a law be unjust if an unjust law is not a law?

## The Positivist Version of the Problem

> The existence of law is one thing; its merit or demerit is another. Whether it be or be not is one enquiry; whether it be or be not conformable to an assumed standard, is a different enquiry.

---

1. Existence
2. Evaluation

## Another Dissent

> Now to say that human laws which conflict with the divine law are not binding, that is to say, are not *laws*, is to talk stark non-sense. [Austin]

Austin's point:

* Unjust laws are not promulgated. But this is false just as plagiarized papers often get turned in.
* Unjust laws are not enforced, but this is also not right.

1. Promulgation
2. Enforcement

> Austin reads the *non-est-lex* slogan as if it entailed the absurd claim that unjust laws are never promulgated or enforced, and then takes himself to have refuted the slogan by pointed out in patronizing detail that they sometimes are.

# The Four Types of Law and the Relations

1. Eternal Law
2. Natural Law
3. Laws of Physics
4. Rational Law

## Eternal Law

* The foundation of the other kinds of law.
* Is God's plan
* providence
* intellect
* i.e., God himself as the ruler of the universe

## Natural Law

* Only in human beings
  * innate principles of rational action
  * human laws derive from it

---

Human laws as derived from moral rules. However:

> It is on the basis of the precepts of natural law, as from general and indemonstrable principles of a certain sort, that human reason must proceed to certain matters that must be dealt with in more detail. And those detailed dispositions, arrived at in accordance with human reason, are called human laws, *provided that the other conditions that pertain to the essence of law have been met.*

# Aquinas' Conception of Natural Law

## What is Natural?

1. Inclination to the self-preservation of life
   1. Why 'self'-preservation and not merely preservation?
   2. 'a human being's' life, not necessarily 'human' life more broadly
2. Inclination towards specific goods
   1. raising offspring etc
3. Inclination to what is good
   1. truth about God
   2. live in society consider 'a human' vs 'human' distinction

## Conscience and Natural Law

> conscience is called the law of our intellect insofar as it is a dispositional state containing the precepts of naural law, which are the first principles of human actions. [11]

1. Precepts of natural law are fundamental moral rules
2. Is unjust law a perversion or counterfeit?

> It is on the basis of the precepts of natural law, as from general and indemonstrable principles of a certain sort, that human reason must proceed to certain matters that must be dealt with in more detail. And those detailed dispositions arrived at in accordance with human reason, are called human laWs, provided thats the other conditions that pertain to the essence of law have been met. [12]

1. What are these 'matters'?
2. How must we deal with them?
3. What are the important dipositions 'arrived at in accordance with human reason'?
   1. human laws
   2. Only if other conditions are met
   3. What are these other conditions?

# Definition and Evaluation in Aquinas' Treatise on Law

1. A directive of reason
2. Aimed at the common good
3. Promulgated by the government
4. Pertaining to a complete community
5. Leading people to or retraiing them from certain actions
6. Having coercive power

# Inclusion Conditions for Law

## 5, Leading people to or restraining them from certain actions

1. An ordinance
2. Dictate
3. Directive

That possibly derives from a directive of reason. But where does 6 (coercive power), come from?

## 6, Coercive Power

Who has coercive power?

1. Soverign
2. Government
3. (Importantly), one *responsible* for the community

## Final Condition

* Intended to be obeyed
  * Related to the laws coercive power

# Non-Evaluative and Evaluative Conditions

Conditions 1 and 2 are very different from conditions 3-6.

## 1 and 2

1. A directive of reason
2. Aimed at the common good

* Evaluative

## 3-6

3. Promulgated by the government
4. Pertaining to a complete community
5. Leading people to or retraiing them from certain actions
6. Having coercive power

* Non-Evaluative

## Examples

Why do household rules fail to satisfy all the conditions?

They satisfy 1 and 2, but not 3-6.

# Aquinas' Assessments of Law

# Laws on Trial in the Court of Conscience
