---
subtitle: "PHIL101B -- Introduction to Philosophy"
title: "<font style='font-size:1em;'>🗓️ Week 6<br/> The Metaphysics of Sim Worlds</font>"
author: Prof. [Reynolds](#)
institute: '[Stetson University](#)'
date: 02 September 2026
date-meta: 14 March 2023
date-format: "DD MMM YYYY"
toc: false
toc-depth: 1
toc-title: "Meta"
center-title-slide: false
from: markdown+emoji
format:
  revealjs:
    theme: moon
    fig-responsive: true
    slide-number: true
    incremental: true
    mouse-wheel: false
    auto-play-media: true
    preview-links: auto
    logo: /figures/icons/course_favicon.png
    css: /css/styles_slides.css
    footer: 'PHIL101B -- Metaphysics of Sim Worlds'
---

# Chapter 6: Reality

Consider simblockers

* Sims can't be conscious
* Simulators will avoid creating conscious sims
* Sims won't have minds like ours
* Sims won't experience large universes

## What is Real?

Chalmer's View:

* Virtual Realism: virtual reality is genuine reality, . . . virtual objects are real and not an illusion.
* Simulation Realism: objects in simulation around us are real and not illusion.
* Virtual digitilism: objects in virtual reality are digital objects, structures of binary information.

## Defining Real

* Reality: Everything that exists
* Reality: World or Worlds
* Reality: a Property

---

### Reality+

* Reality contains many realities
* Each of these realities are real

> Or more mundanely: the cosmos (everything that exists) contains many worlds (physical and virtual spaces), and the objects in those worlds are real.

# The Really Real

* Reality as existence
* Reality as causal power
* Reality as mind independence
* Reality as non-illusoriness
* Reality as genuineness


