---
subtitle: "PHIL101B -- Mind Part 2"
title: "<font style='font-size:1em;'>🗓️ Week 12 or so<br/>Chapter 15 and 16</font>"
author: Prof. [Reynolds](#)
institute: '[Stetson University](#)'
date: 02 September 2026
date-meta: 14 March 2023
date-format: "DD MMM YYYY"
toc: false
toc-depth: 1
toc-title: "Consciousness"
center-title-slide: false
from: markdown+emoji
format:
  revealjs:
    theme: moon
    fig-responsive: true
    slide-number: true
    incremental: true
    mouse-wheel: false
    auto-play-media: true
    preview-links: auto
    logo: /figures/icons/course_favicon.png
    css: /css/styles_slides.css
    footer: 'PHIL101B -- Mind Part 2'
---

# A History of the Philosophy of Mind

## {background-image=./city-scape.jpg}

::: {.columns}

::: {.column width="40%"}

:::

::: {.column width="60%"}

::: {.fragment .highlight-red .r-text-fit}

* Neolithic burial practices
* Trojan War
* Reformation
* Descartes
* &#1488;&#1492;&#1497;&#1492; &#1488;&#64298;&#1498; &#1488;&#1492;&#1497;&#1492;
  * I am that I am?
  * I will be that which I wish to be

:::

:::

:::

::: {.notes}

* Questions about the nature of conscious awareness have likely been asked for as long as there have been humans.
*  Neolithic burial practices appear to express spiritual beliefs and provide early evidence for at least minimally reflective thought about the nature of human consciousness (Pearson 1999, Clark and Riel-Salvatore 2001).
  * Memory often defined as a social and cultural phenomenon . . . used to refer to perceived and imagined pasts shared between people [@stut13]
* (Ehyeh Asher Ehyeh / YHWH), where the relative pronoun asher (“that”, “who”, “which”, and “where”) is between two instances of the first person singular imperfect of the verb hayah (“to be”). Ehyeh is often, but not always, translated as “I will be”, while the relative pronoun can have several meanings: “I will be that/who/which/where I will be”. It is maybe translated most basically as “I Am that/who/which/where I Am“,

:::

## {.fragment .highlight-red background-image=./jump-seat.jpg}

::: {.columns}

::: {.column width="40%"}

:::

::: {.column width="60%"}

> I do not say there is no soul in man because he is not sensible of it in his sleep. But I do say he can not think at any time, waking or sleeping, without being sensible of it. Our being sensible of it is not necessary to anything but our thoughts, and to them it is and to them it always will be necessary. [@lock88]

:::

:::

## {background-image=./across-time.jpg}

* Sentience
* Wakefulness
* Self-consciousness
* Phenomenal Experience (What it's like)
* Subjects of conscious states
* Transitive Consciousness

::: {.notes}

* Sentience: sensing and responding to the world
* Wakefulness: exercising a capacity, say awakeness
* Self-consciousness: aware that one is aware.
* Phenomenal
  * One important tenent of naturalism, is just how do experiences we have map onto what our observations says that we are saying. Consciousness, Nagel argues, means "what it is like" to be that animal.

:::

# References
