---
subtitle: "SCHF: The Experience Machines"
title: "<font style='font-size:1em;'>🗓️ Week 08<br/> Reality+, Up to Chapter 10</font>"
author: Prof. [Reynolds](#)
institute: '[Stetson University](#)'
date: 02 September 2026
date-meta: 14 March 2023
date-format: "DD MMM YYYY"
toc: false
toc-depth: 1
toc-title: "The Art of Imitation:"
center-title-slide: false
from: markdown+emoji
format:
  revealjs:
    theme: moon
    fig-responsive: true
    slide-number: true
    incremental: true
    mouse-wheel: false
    auto-play-media: true
    preview-links: auto
    logo: /figures/icons/course_favicon.png
    css: /css/styles_slides.css
    footer: 'PHIL343A -- Aesthetics Aristotle'
---

# So, Do VR Headsets Create Reality?

* Can we know that we are in a simulation?
  * No, but neither can we not know that we are in a simulation.

* Some important thought experiments:
  * Zhuangzi's Butterfly Dream
  * Narada's Transformation
  * Roy, A life well lived
  * Plato's Cave

## Three Important Questions:

* How can Zhuangzi *know* whether or not he is dreaming?
* Is Narada's transformation real or illusory?
* Can we live a good life in Plato's cave?

## The simulation hypothesis

* Four phases of simulation:

1. Representation
2. Could
3. Could have
4. simulcrum: possible worlds

---

We can look at ways that Elite Dangerous or Star Citizen represent the way the world is now, or the way it could or could have been, we use Elite or SC in ways that bare no resemblance at all to reality.

# Simulation Hypothesis

* We are living in a simulation.
* We are and have always been in a computer simulation of the world.

## Two Kinds of Sims

* Biosim: biological sims outside the simulation
  * Inhabit impure sims
* Pure sim: simulated beings wholly inside simulation
  * Inhabit: pure sims

* Local simulations: simulate part of the simulation
* Global simulations: simulates the whole universe

# What is the likelihood that we are in a sim?

1. At least one in ten nonsim populations will each create a thousand sim populations
2. If at least one in ten nonsim populations will each create a thousand sim populations, then at least 99 percent of intelligent beings are sims.
3. If at least 99 percent of intelligent beings are sims, we are probably sims.
4. Therefore, we are probably (likelihood is more than .5) sims.

## Why might we think 1 is false?

* It will never happen:
  * simulation is too difficult
  * simulation is impossible
  * nonsim populations will all die before creating sims
  * nonsims will choose not to create sims

## It is too difficult

* Intelligent sim creation is impossible
  * uncomputable
  * physical brain processes cannot be simulated
* Takes too much power
  * brains have 100 billion neurons, 1000 connections (synapses) each, 10 quadrillion (10$^16$) floating point operations per second

# What is Reality?

Inital claim:

* Physical things are the only real things.
* Virtual Realism: virtual things are real too
  * Realism: something is real
  * virtual reality is genuine reality
  * virtual objects are real and not an illusion
  * simulation realism: If we are in a simulation, the objects around us are real and not an illusion.

# External World Skepticism and the Simulation Argument

## We cannot know that the world around us is real

::: {.r-fit-text}

* Knowledge of the external world
  * JTB: Knowledge = justified true belief
  * To know something, you have to *think* it's true (belief), you have to be *right* about it (belief is true), you have to have good *reasons* for believing it (belief is justified).
* Skepticism about knowledge of the external world
  * skeptic: someone who casts doubt on our beliefs about a certain domain
  * global skepticism: doubts all our beliefs, we cannot know anything at all.
* Cartesian skepticism: skepticism of the external world
  * Not global since we can have inferential knowledge, and analytic knowledge, or logic, or knowledge of our own minds (cogito, I think therefore I am).

:::

## Why Cartesian Skepticism? Simulation Argument

::: {.r-fit-text}

* Our senses have deceived us in the past, why should we think they are not deceiving us now. (I mistake an adversary NPC for an inanimate virtual object and am shot and killed.
  * Virtual reality devices have fooled people before, how do we know a VR device isn't fooling us now?
  * Dreams are like reality, how do we know we're not dreaming now?
* An all powerful demon could be deceiving us, how do we know that one is not?
  * Evil scientist, brain in a vat (Hilary Putnam): computer sends electronic impulses to the brain, bringing about illusion that everything is normal
  * Evil Game Designer:
  * Simulation Hypothesis: An all masterful game developer could have created a device and connected it to us while we were sleeping.
* Master Argument:
  * You cannot know that you're not in a simulation
  * If you cannot know you're not in a simulation, you can't know anything about the external world
  * So, you can't know anything about the external world

:::
