---
subtitle: "PHIL284 -- Law"
title: "<font style='font-size:1em;'>🗓️ Week 06<br/> The Crito</font>"
author: Prof. [Reynolds](#)
institute: '[Stetson University](#)'
date: 02 September 2026
date-meta: 14 March 2023
date-format: "DD MMM YYYY"
toc: false
toc-depth: 1
toc-title: "Justice and Law"
center-title-slide: false
from: markdown+emoji
format:
  revealjs:
    theme: moon
    fig-responsive: true
    slide-number: true
    incremental: true
    mouse-wheel: false
    auto-play-media: true
    preview-links: auto
    logo: /figures/icons/course_favicon.png
    css: /css/styles_slides.css
    footer: 'PHIL284 -- The Crito'
---

# Crito


In the Crito, Socrates is awaiting his execution in an Athenian prison on charges of impiety against the recognized Athenian gods, and corrupting the youth of Athens. For his punishment, Socrates will forced to commit suicide by drinking the deadly poison hemlock.

---

> “No, it hasn't arrived, but it looks like it will arrive today, based on the report of some people who have come from Sounion\* and who left when it was there. It's clear from this that it will arrive today, and you will have to end your life tomorrow, Socrates.” ([Woods and Pack, 2022, p. 1](zotero://select/library/items/UL9YYE69)) ([pdf](zotero://open-pdf/library/items/U2LAYDCM?page=3&annotation=83YTGSEI))

---

Crito, a prominent Athenian citizen has entered Socrates' cell while Socrates was still asleep.

* Has already bribed the Jailer
* Has already arranged for Socrates escape to Thessaly
* Socrates would remain in exile with his family for the rest of his life

---

Reasons for escape Sense of Honor, Obligation to Others:


* Eternal Separation from Friends and Family
* Friends will be accused of being unfaithful
* Betraying Family, prioritizing Athenian laws over and above family: Betrayal
* Satisfying the desires of his enemies
* The trial and conviction were utterly unnecessary

## Three Arguments

::: {.r-fit-text}

* If Socrates is executed, then he and others will lose an irreplaceable friend. Moreover, people will wonder why Socrates’ friends didn’t do more to save his life when they had the means to do so. They’ll ask: Is Crito such a cheapskate that he refused to part with a little money to save his friend’s life? (44c)
* Socrates also has obligations to raise and educate his sons, who will be fatherless if Socrates is executed (45d).
* Finally, in passively accepting his unjust fate, Socrates will be giving his enemies what they want, allowing evil to triumph. Death is the easy, cowardly way out. To continue living is more difficult and courageous. Escaping would deny evil a victory (45e-46a).

:::

## Obligation to Friends

> “If you die, for me it won't be just one misfortune: apart from being separated from the kind of friend the like of which I will never find again, many people, moreover, who do not know me and you well will think that I could have saved you if I were willing to spend the money, but that I didn't care to. And wouldn't this indeed be the most shameful reputation, that I would seem to value money above friends? For the many will not believe that it was you yourself who refused to leave here, even though we were urging you to.” ([Woods and Pack, 2022, p. 2](zotero://select/library/items/UL9YYE69)) ([pdf](zotero://open-pdf/library/items/U2LAYDCM?page=4&annotation=Q2LNUMTE))

---

* Friends will loose a close friend
* Friends will suffer poor reputation

---

* If you die, I will loose a friend
* People will think that I showed vice, prioritizing money over friendship

## Obligation to Family

> In addition, I think you are betraying your sons, whom you could
raise and educate, by going away and abandoning them, and, as far as you
are concerned, they can experience whatever happens to come their way,
when it's likely that as orphans they'll get the usual treatment of orphans.
One should either not have children or endure the hardship of raising and
educating them, but it looks to me as though you are taking the laziest
path, whereas you must choose the path a good and brave man would
choose, especially when you keep saying that you care about virtue your
whole life long.

---

Obligations:

* Raise and Educate
* Leaving their care to fate
* They will experience hardship
* Socrates is taking the easy way out
  * Vicious, failure to display virtue
  * Cowardice, a vice

---

::: {.r-fit-text}

* One should either [not have children] or [endure the hardship of raising and
educating them]
* You have children
* Therefore, you have chosen to endure the hardship of raising and educating them
* But [By choosing not to escape] you have chosen to abandon your sons (a contradiction)
* Because you have chosen to abandon your sons, you have chosen to not raise and educate your sons
* Therefore you are betraying your sons
* You have allowed them to experience whatever happens to come their way [usual fate of orphans]
* Therefore you are vicious
:::

---

Public Opinion:

> “But why, blessed Crito, should we care so much about the opinion of the many?”

---

Socrates' Response, argument from expertise:

::: {.r-fit-text}

* “So, then, what did we say, again, about cases such as this: should a man in training, who takes it seriously, pay any heed to the praise and blame and opinion of everyone, or only to one person, the one who is a doctor or a trainer?” ([Woods and Pack, 2022, p. 4](zotero://select/library/items/UL9YYE69)) ([pdf](zotero://open-pdf/library/items/U2LAYDCM?page=6&annotation=RAUAM6RR))
* “Have a look, then. Is it fair enough to say that one should not value every human opinion but only some and not others?” ([Woods and Pack, 2022, p. 4](zotero://select/library/items/UL9YYE69)) ([pdf](zotero://open-pdf/library/items/U2LAYDCM?page=6&annotation=WK36HXRV))
* “Shouldn't we value the good opinions, and not the worthless ones?” ([Woods and Pack, 2022, p. 4](zotero://select/library/items/UL9YYE69)) ([pdf](zotero://open-pdf/library/items/U2LAYDCM?page=6&annotation=JCZQQQIN))
* “Aren't the good ones the opinions of the wise, while the worthless ones come from the ignorant?” ([Woods and Pack, 2022, p. 4](zotero://select/library/items/UL9YYE69)) ([pdf](zotero://open-pdf/library/items/U2LAYDCM?page=6&annotation=X2VCPI3D))
* “If they were of any use, Crito, the many would be able to do the greatest evils, and so they would also be able to do the greatest goods, and that would be fine.” ([Woods and Pack, 2022, p. 2](zotero://select/library/items/UL9YYE69)) ([pdf](zotero://open-pdf/library/items/U2LAYDCM?page=4&annotation=IYDVH9MX))

* “But as it is they can do neither, since they cannot make a man either wise or foolish, but they do just whatever occurs to them.” ([Woods and Pack, 2022, p. 2](zotero://select/library/items/UL9YYE69)) ([pdf](zotero://open-pdf/library/items/U2LAYDCM?page=4&annotation=XTZ95XRX))

:::

::: {.notes}

“So, then, what did we say, again, about cases such as this: should a man in training, who takes it seriously, pay any heed to the praise and blame and opinion of everyone, or only to one person, the one who is a doctor or a trainer?” ([Woods and Pack, 2022, p. 4](zotero://select/library/items/UL9YYE69)) ([pdf](zotero://open-pdf/library/items/U2LAYDCM?page=6&annotation=RAUAM6RR))

“So, he should fear the criticisms and welcome the praises of that one person, and not those of the many?” ([Woods and Pack, 2022, p. 4](zotero://select/library/items/UL9YYE69)) ([pdf](zotero://open-pdf/library/items/U2LAYDCM?page=6&annotation=F4VV9U25))

“He must practice and exercise, and eat and drink, in the way that seems best to that one person, the trainer and expert, more than to all the others together.” ([Woods and Pack, 2022, p. 4](zotero://select/library/items/UL9YYE69)) ([pdf](zotero://open-pdf/library/items/U2LAYDCM?page=6&annotation=GCBY87PG))

“Well then. If he disobeys this one man and dishonors his opinion and his praises and instead honors those of the many who know nothing, won't he suffer harm?” ([Woods and Pack, 2022, p. 4](zotero://select/library/items/UL9YYE69)) ([pdf](zotero://open-pdf/library/items/U2LAYDCM?page=6&annotation=8EKPJ6AR))

“What is this harm, and what does it tend to do, and in what part of the disobedient person?” ([Woods and Pack, 2022, p. 4](zotero://select/library/items/UL9YYE69)) ([pdf](zotero://open-pdf/library/items/U2LAYDCM?page=6&annotation=A5X4BWN4))

“It's clear that it's in the body, since this is what it destroys.” ([Woods and Pack, 2022, p. 4](zotero://select/library/items/UL9YYE69)) ([pdf](zotero://open-pdf/library/items/U2LAYDCM?page=6&annotation=9GHH9AJ7))

“but in particular justice and injustice and shameful and fine things and good and bad, which are what our current discussion is about” ([Woods and Pack, 2022, p. 4](zotero://select/library/items/UL9YYE69)) ([pdf](zotero://open-pdf/library/items/U2LAYDCM?page=6&annotation=CRWPLU76))

“If we do not heed his opinion we will corrupt and harm that part of us which becomes better with justice and is destroyed by injustice. Or don't you think so?” ([Woods and Pack, 2022, p. 4](zotero://select/library/items/UL9YYE69)) ([pdf](zotero://open-pdf/library/items/U2LAYDCM?page=6&annotation=W9N58ALY))

“Tell me, if we do not follow the opinion of the person who knows and so destroy that part of us which is improved by what is wholesome and corrupted by what sickens, is life worth living when that part is ruined? This is the body, I suppose, isn’t it?” ([Woods and Pack, 2022, p. 4](zotero://select/library/items/UL9YYE69)) ([pdf](zotero://open-pdf/library/items/U2LAYDCM?page=6&annotation=7FAHEIXZ))

“And is life worth living after the part of us which injustice injures” ([Woods and Pack, 2022, p. 4](zotero://select/library/items/UL9YYE69)) ([pdf](zotero://open-pdf/library/items/U2LAYDCM?page=6&annotation=UG3RZAHX))

“and justice benefits has been corrupted?” ([Woods and Pack, 2022, p. 5](zotero://select/library/items/UL9YYE69)) ([pdf](zotero://open-pdf/library/items/U2LAYDCM?page=7&annotation=PCGN3UK4))

“but living well.” ([Woods and Pack, 2022, p. 5](zotero://select/library/items/UL9YYE69)) ([pdf](zotero://open-pdf/library/items/U2LAYDCM?page=7&annotation=JT7TMCC7))

“whether it is just or unjust for me to try to leave here, when I was not acquitted by the Athenians.” ([Woods and Pack, 2022, p. 5](zotero://select/library/items/UL9YYE69)) ([pdf](zotero://open-pdf/library/items/U2LAYDCM?page=7&annotation=EYGM4TPG))

“As for the points you make about spending money and reputation and the upbringing of children, Crito, I suspect that these are really questions belonging to people who would casually put someone to death and resurrect him, if they could, without any thought—to the members of the multitude.” ([Woods and Pack, 2022, p. 5](zotero://select/library/items/UL9YYE69)) ([pdf](zotero://open-pdf/library/items/U2LAYDCM?page=7&annotation=N5NEHSZV))

“And so, one must never act unjustly.” ([Woods and Pack, 2022, p. 6](zotero://select/library/items/UL9YYE69)) ([pdf](zotero://open-pdf/library/items/U2LAYDCM?page=8&annotation=EBHZ9AKH))

“And so, one should not repay an injustice with an injustice, as the many think, since one should never act unjustly.” ([Woods and Pack, 2022, p. 6](zotero://select/library/items/UL9YYE69)) ([pdf](zotero://open-pdf/library/items/U2LAYDCM?page=8&annotation=RK6L6PN4))

“What next? Should one cause harm, Crito, or not?” ([Woods and Pack, 2022, p. 6](zotero://select/library/items/UL9YYE69)) ([pdf](zotero://open-pdf/library/items/U2LAYDCM?page=8&annotation=LJRTZSAC))

“And then? Is returning a harm for a harm just, as the many say, or not just?” ([Woods and Pack, 2022, p. 6](zotero://select/library/items/UL9YYE69)) ([pdf](zotero://open-pdf/library/items/U2LAYDCM?page=8&annotation=GCJPAHQI))

“And see to it, Crito, that in agreeing with this you are not agreeing contrary to what you believe, because I know that few people believe it or will believe it.” ([Woods and Pack, 2022, p. 6](zotero://select/library/items/UL9YYE69)) ([pdf](zotero://open-pdf/library/items/U2LAYDCM?page=8&annotation=2K4JFHU4))

“And so, there is no common ground between those who hold this belief and those who don't; when they see each other's positions they are bound to despise one other.” ([Woods and Pack, 2022, p. 6](zotero://select/library/items/UL9YYE69)) ([pdf](zotero://open-pdf/library/items/U2LAYDCM?page=8&annotation=9YDNVV7G))

“By attempting this deed, aren't you planning to do nothing other than destroy us, the laws, and the civic community, as much as you can?” ([Woods and Pack, 2022, p. 7](zotero://select/library/items/UL9YYE69)) ([pdf](zotero://open-pdf/library/items/U2LAYDCM?page=9&annotation=6ZMJ2S8G))

:::
