---
subtitle: "PHIL284 -- H.L.A. Hart"
title: "<font style='font-size:1em;'>🗓️ Week 8<br/>Blame and Punishment</font>"
author: Prof. [Reynolds](#)
institute: '[Stetson University](#)'
date: 02 September 2026
date-meta: 14 March 2023
date-format: "DD MMM YYYY"
toc: false
toc-depth: 1
toc-title: "Hume"
center-title-slide: false
from: markdown+emoji
format:
  revealjs:
    theme: moon
    fig-responsive: true
    slide-number: true
    incremental: true
    mouse-wheel: false
    auto-play-media: true
    preview-links: auto
    logo: /figures/icons/course_favicon.png
    css: /css/styles_slides.css
    footer: 'PHIL284A -- Hart'
---

# Punishment for the utilitarian seems to be a contradiction.

## Retributive Punishment (Retributivist)

***Bentham:***

> Nature has placed mankind under the governance of two sovereign masters, *pain*, and *pleasure*.

---

In other words

* Every action either promotes pleasure, or mitigates pain.
* Therefore, we evaluate all action by its ability to promote pleasure or mitigate pain.

How does punishment do either?

---

Ultimately, there needs to be some good attached to punishment:

* But what is the good that is attached to punishment?

> Other institutions have benefits associated with them, yet institutions in charge of distributing punishment seem to offer no such benefit.

---

Let's consider the suffering of the wrong doer in contrast with the nature of the offence committed:

1. Laws are intended to mitigate pain

But the harm is already done, it is impossible to mitigate a harm that has already occurred.

2. Laws intended to Promote pleasure

---

Punishment does not seem to promote pleasure given that the harm has already occurred.

1. Mitigating pain is forward looking
2. Promoting pleasure is also forward looking
3. Punishment is backward looking

> All justifications for punishment, indeed all justifications for anything, are forward-looking in the sense that they explain how the justified thing promises to make the world a better place, or at least to avoid its getting any worse. (John Gardner, Introduction)

---

As such, what justifies the retributive view?

> Presumably this has contributed to the use near synonym for "reason for". Which i minor determinant of the modern fashion-for which there is much  to be said-of presenting moral philosophy as an enquiry into what are and are not good reasons in ethics. (Anthony Flew, The Justification of Punishment, 296)

## Two Possibilities

* Intrinsic Value of the suffering of the accused
* Extrinsic value of the suffering of the accused

> The special feature of the retributive view, rather, is that it finds some intrinsic-not merely instrumental-value in a certain type of suffering, namely in suffering that is deserved.

## Extrinsic value of suffering

> "Punishment is punishment only where it is deserved. We must pay the penalty because we owe it, and for no other reason. If punishment is inflicted for any other reason whatever than because it is merited by a wrong, it is a gross immorality, an abominable wrong crime." (Ethical Studies, pp. 26-7).

---

> This is similar same as Mabbott's position. Not the same; because Mabbotts dissents from most upholders of the retributive theory---from Hegel, from Bradley, and from Dr. Ross" (loc. cit., p. 154) on the grounds that the essential link is between "crime" and "punishment" and not between "doing wrong" and "punishment".

## What is the “rationale of the doctrine of mens rea,”:

Criminal Culpability Requires:

1. Knowledge
2. Intention
3. Control

---

However, two important issues keep arising for the retributivist:

* Moral
* Practical

## The Two Issues

> An intention to do the act which is made penal by statue or by the common law

or

Jerome Powell:

> though the goodness or badness of the motive with which a crime is committed may not be relevant, the general principle of liability, except of course where liability is unfortunately 'strict' and so any mental element must be disregarded, is the (intentional or reckless doing of a morally wrong act'. [36]

---

> It is characteristic of our own and all advanced legal systems that the individual's liability to punishment, at any rate for serious crimes carrying severe penalties, is made by law to depend, among other things, on certain mental conditions. These conditions can best be expressed in negative form as excusing conditions: the individual is not liable to punishment if at the time of his doing what would otherwise be a punishable act he was unconscious, mistaken about the physical consequences of his bodily movements or the nature or qualities of the thing or persons affected by them, or, in some cases, if he was subjected to threats or other gross forms of coercion or was the victim of certain types of mental disease.

---

Voluntariness, or excusing conditions:

1. Conscious
2. Not Mistaken about the physical consequences of his bodily movements
3. Nature or quality of things affected by them
4. Not subjected to threats or other forms of coercion
5. Mentally well

---

Response Grounded in Determinism:

1. It may be true that human conduct (actions; movements and cognitive activity, are subject to laws)
2. If human conduct is subject to laws, the distinction between acts that fall under excusing conditions as above, and those that do not are not important

---

Consider: Acts that fall under excusing conditions that those that invalidate civil arrangements (wills, gifts, contracts, and marriages).

A careful expression of determinism:

> This more cautious determinist says that whatever the expressions 'voluntary', etc. may mean, unless we have reasonable grounds for thinking there are no such laws, the distinctions drawn by these expressions cannot be regarded as of any importance, and there can be neither reason nor justice in allowing punishment to depend on the presence or absence of excusing conditions.

## Mens Rea

Subjective element of criminal responsibility:

* Mental health
* knowledge of act
* believed about the act
* not under compulsion

---

What actions fall under these?

1. Strict liability: accused is ignorant of the facts of the legality of the act
  1. Still liable to punishment
2. Non-strict liability: act was unintentional

---

Human capacity to control behavior:

1. volitional control over body
2. physical character of movements and their consequences
3. unable to resist "urge"
   1. typically surrounding physiological or neurological symptoms.

## What is wrong with strict liability?

1. Criminal responsibility $\rightarrow$ moral responsibility
2. Or "intention" to do the act

---

> though the goodness or badness of the motive with which a crime is committed may not be relevant, the general principle of liability, except of course where liability is unfortunately 'strict' and so any mental element must be disregarded, is the (intentional or reckless doing ofa morally wrong act'.

Mens Rea:

1. Volitional control over body
2. Physical character of movements and their consequences
3. Unable to resist "urge"
4. Act is morally wrong

---

From the above, we derive "Criminal Culpability requires . . .":

1. Strict = based on outward conduct of the accused
2. Or based on moral culpability

---

However, this means that there is no reason to inquire of the mental state of the accused.
