---
subtitle: "PHIL101B -- As though it is the case"
title: "<font style='font-size:1em;'>🗓️ Week 09<br/> The realness of virtual</font>"
author: Prof. [Reynolds](#)
institute: '[Stetson University](#)'
date: 02 September 2026
date-meta: 14 March 2023
date-format: "DD MMM YYYY"
toc: false
toc-depth: 1
toc-title: "The Art of Imitation:"
center-title-slide: false
from: markdown+emoji
format:
  revealjs:
    theme: moon
    fig-responsive: true
    slide-number: true
    incremental: true
    mouse-wheel: false
    auto-play-media: true
    preview-links: auto
    logo: /figures/icons/course_favicon.png
    css: /css/styles_slides.css
    footer: 'PHIL108B -- Introduction'
---

# Virtual Worlds?

## Knowledge?

## Reality?

## Chapter 6

---

### What is reality?

Physical Realism: Physical things are the only things that's real

* Physical things are real.
* Only physical things are real.
* Virtual things are not real.

---

Virtual Realism:

* Physical things are physically real
* Virtual things are virtually real

---

> As I understand it, virtual realism is the thesis that virtual reality is genuine reality, with emphasis especially on the view that virtual objects are real and not an illusion.

Simulation Realism: If we are in a simulation, then the things around us are real

Virtual digitialism: Objects in virtual reality are digital (not physical) objects

---

### Reality and Realities

Defining Reality: 3 Points

* Everything that exists, the entire cosmos
* A world or worlds, either multiverse, virtual spaces, physical or virtual
* A property, rigidity, property of being real

---

### Five ways of thinking about what's real

* Existence: exists, ""What is it to exist?" This is a deep question, to which I can’t give a definitive answer."
  * Berkeley, esse is percipi
  * But there could be real things that we might never perceive
* Causal Power
  * Eleatic dictum: to be real is to have causal powers.

---

> “I suggest that everything which possesses any power of any kind, either to produce a change in anything of any nature or to be affected even in the least degree by the slightest cause, though it be only on one occasion, has real being.”

* Mind-independence
  * We can call it Philip K. Dick’s dictum: “Reality is that which, when you stop believing in it, doesn’t go away.”
* Non-illusoriness
* Genuiness

---

### Is simulated reality real?

::: {.r-fit-text}

Reality means one or more of the criteria below. How would David Chalmers check the boxes below? Pay attention to the reasons he gives. How would David Deutsch check the boxes below?

* Criterion for reality:
  - [ ] Do the objects we perceive in this simulated world really exist?
  - [ ] Do the objects we perceive have causal powers?
  - [ ] Are the objects we perceive independent of the mind?
  - [ ] Are things as they seem to be?
  - [ ] Are the things I experience in a simulation real flowers, and real books, and real people?

:::

---

> I defend simulation realism this way: "If we're in a perfect simulation, the objects around us are real and not an illusion." The reference to illusion puts the greatest weight on the fourth criterion: Simulation realism holds that things are largely as we believe them to be. [@chal22]

---

#### What are the objections?

::: {.r-fit-text}

Consider what David Deutsch says in his 1997 book *The Fabric of Reality*:

* Who do you agree with?
  * [ ] Chalmers?
  * [ ] Deutsch?
* If we are in a perfect simulation:
  * Which beliefs are right?
  * Which beliefs are wrong?
* If we are in an imperfect simulation:
  * Which beliefs are right?
  * Which beliefs are wrong?

:::

---

### The simulation hypothesis as metaphysics

What is the implication of the it-from-bit thesis:

* If we are living in a simulation?
* If we are not living in a simulation?
* Why isn't the simulation hypothesis a skeptical hypothesis?
* What is it equivalent to?

---

### The no-illusion view in the history of philosophy

What about objects in a Cartesian scenario? What are their natures?

* Descartes's evil-demon scenario?
* Hilary Putnam's brain-in-a-vat scenario?

How does David Chalmers respond to the skeptic in these scenarios?

::: {.notes}

Descartes's evil-demon and Hilary Putnam's brain-in-a-vat scenarios are sceptical views about our ability to know facts about our world. The sceptic argues that we do not know anything. Descartes famously offers a solution suggesting that first, he is a thinking thing, and then uses reason to deduce that God would not want him to be deceived. Still, according to the epistemic sceptic, it is possible that we do not know anything and each offers varying rebuttals. The following thought experiments show us some possible complications and responses.

In Descartes's evil-demon thought experiment, Descartes argues that it is possible that an evil demon has deceived us. In Hillary Putnam's brain-in-a-vat scenario, he imagines someone waking up in a lab. Unfortunately for the hapless individual however, this person does not realize that he has awoken in a lab. This is because this individual has been connected to a machine that feeds him the content of all his perceptions. According to Descartes, all of our perceptions are based on an illusion. Similarly in Putnam's example, the perceptions of the hapless individual are being fed to them by a machine. Therefore, the contents of all perceptions are all being manufactured by the demon or created by a machine. It is possible that we are the hapless individuals and would not know otherwise. Any belief that we have, that is based on the illusion created by the evil demon will be false according to the sceptic. Using this possibility, Descartes, like Putnam, argues that all of our beliefs about the outside world are false. However, Chalmers defends what he calls the no-illusion view. According to Chalmer's view, if we are living in a world manufactured by the evil demon, then it is not true that the objects of our perceptions are illusions, but rather that the objects of our perceptions are real. Their underlying nature however may not be what we thought it was.

:::

---

What are some possible similar responses?

* What might George Berkeley's response be to the evil demon scenario?
* What is another thought experiment similar to the evil demon? Contrast it with Chalmer's view
  * What makes something an illusion?
  * What about illusions that cannot be discovered?
  * How does Chalmers respond? What about Bouwsma?

::: {.notes}

If one is in a perfect simulation, then the things inside that simulation are perfectly real according to Chalmers. This is because according to the no-illusion view, in a skeptical scenario such as the evil-demon or even the brain-in-a-vat scenario, an object's nature is largely as it appears, the flower that I am perceiving, even though created by the machine, really is a flower.

Descartes's response is often called a form of foundationalism grounded in what is called rationalism. Knowledge begins with some base or foundation. For Descartes, this base or foundation is the cogito "I think therefore I am". George Berkeley offers a response that is similar to Chalmers's own view. According to Berkeley, appearance is reality. Therefore if I perceive a given object, then that object is reality for me. Whether I am living in a dream-like state, an illusion created by an evil demon, or a simulation created by a scientist.

:::

---

* Idealism
* Verificationism: meaningful claims are verifiable.
  * Rudolf Carnap and other logical positivists
  * How does Chalmers respond to logical positivists?
---

## Is God a hacker in the next universe up?



## Is the universe made up of information?

## Did simulation create its from bits?

# Real Virtual Reality?

## Do virtual reality headsets create reality?



---

### What is reality?

(Charles Sanders Peirce): “A virtual X (where X is a common noun) is something, not an X, which has the efficiency (virtus) of an X.”

(Antonin Artaud):

> All true alchemists know that the alchemical symbol is a mirage as the theater is a mirage. And this perpetual allusion to the materials and the principle of the theater found in almost all alchemical books should be understood as the expression of an identity (of which alchemists are extremely aware) existing between the world in which the characters, objects, images, and in a general way all that constitutes the virtual reality of the theater develops, and the purely fictitious and illusory world in which the symbols of alchemy are evolved.

Dave Chalmers: A virtual reality environment is an immersive, interactive, and computer-generated space.

- Interactive: means that there’s two-way interaction between users and the environment, and among objects in the environment.

- Computer-Generated: a computer is generating the signals that are sent to our sensory systems.

- Immersive: means that we experience the environment as a world all around us, with ourselves present at the center.
  - psychologically immersive: occupying all of our attention in a sort of flow state
  - perceptually immersive: the world as a three-dimensional world surrounding us.
  - audiovisual immersion: the environments look and sound as if you’re immersed in them.
  - bodily immersion: the environments look and sound as if you’re immersed in them.
  - full immersion: "A fully immersive or full-dive VR is one that users apprehend with all their senses, as if they’re physically inhabiting the environment, and where no trace of the ordinary physical environment remains."

Susanne Langer: Virtual worlds
- objects
- space
- powers
- memory


## Are virtual reality devices illusion machines?

## Does augmented reality lead to alternative facts?

# Mind

## How do mind and body react in a virtual world?

## Can there be consciousness in a digital world?

## Does augmented reality extend the mind?

# Value

## Can you lead a good life in a virtual world?

## Do Simulated lives matter?

## How should we build a virtual society?

# Foundations

## What do our words mean in virtual worlds?

## Do dust clouds run computer programs?

## Is reality a mathematical structure?

## Have we fallen from the garden of Eden?

## Are we Boltzman brains in a dream world?




